apiVersion: v1
kind: Service
metadata:
  name: demo-1-service
  labels:
    name: demo-1-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: demo-1
  type: LoadBalancer
